title: Decentralized Applications
author: Muhammad Adil Hussain
email: adilhussain540@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This site is all about what is going on in Decentralized Applications and Blockchain domain. If you are interested, sit back and turn your notifications ON.
  If you are interested in contributing, contact the author on provided handles.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
